/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    features: Feature;
    'use-cases': UseCase;
    'pricing-tiers': PricingTier;
    'faq-items': FaqItem;
    'form-submissions': FormSubmission;
    'deployment-locations': DeploymentLocation;
    'client-logos': ClientLogo;
    media: Media;
    claims: Claim;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'use-cases': UseCasesSelect<false> | UseCasesSelect<true>;
    'pricing-tiers': PricingTiersSelect<false> | PricingTiersSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'deployment-locations': DeploymentLocationsSelect<false> | DeploymentLocationsSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Articles published on the blog. Supports SEO metadata and multi-language.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  category?: (number | null) | BlogCategory;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  readingTime?: number | null;
  status?: ('draft' | 'published') | null;
  /**
   * Required with Published status before public rendering/indexing.
   */
  isVisible?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  provenanceStatus: 'unreviewed' | 'real-redacted' | 'real-public' | 'illustrative-sample' | 'conceptual';
  source?: string | null;
  owner?: string | null;
  capturedAt?: string | null;
  permissionStatus: 'unreviewed' | 'approved' | 'restricted' | 'expired';
  approvedLocales?: ('en' | 'id')[] | null;
  approvedRoutes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  reviewAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Required before this category can render publicly.
   */
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('super_admin' | 'editor' | 'viewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Product features shown on the Features page and homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * Locale-independent capability identifier.
   */
  stableId: string;
  name: string;
  slug: string;
  /**
   * Lucide icon name (e.g. "users", "flame")
   */
  icon?: string | null;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  useCaseExamples?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  relatedFeatures?: (number | Feature)[] | null;
  image?: (number | null) | Media;
  productTruth: {
    solutionType: 'shared' | 'retail' | 'mall';
    publicAvailability: 'available' | 'deployment-dependent' | 'pilot' | 'roadmap' | 'not-public';
    commercialEntitlement: 'core' | 'add-on' | 'proposal' | 'not-public';
    requirements?: {
      cctv?: boolean | null;
      sensor?: boolean | null;
      gpu?: boolean | null;
      pos?: boolean | null;
      floorPlan?: boolean | null;
      network?: boolean | null;
      other?: string | null;
    };
    inputAndPrerequisites?: string | null;
    outputDefinition?: string | null;
    unitAndTimeWindow?: string | null;
    updateBehavior?: string | null;
    measurementScope?: string | null;
    retailMeaning?: string | null;
    mallMeaning?: string | null;
    decisionSupported?: string | null;
    limitationsAndValidation?: string | null;
  };
  evidence: {
    mediaStatus: 'real-redacted' | 'illustrative-sample' | 'conceptual-flow' | 'none';
    owner?: string | null;
    reviewedAt?: string | null;
  };
  /**
   * Approved claim records supporting public copy.
   */
  claimRecords?: (number | Claim)[] | null;
  publiclyApproved?: boolean | null;
  sortOrder?: number | null;
  isVisible?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Approval records for public product, proof, and service claims.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  key: string;
  /**
   * Exact sentence approved for public use.
   */
  approvedSentence: string;
  claimType:
    'capability' | 'performance' | 'customer' | 'deployment' | 'privacy' | 'commercial' | 'technical' | 'service';
  status: 'draft' | 'approved' | 'expired' | 'rejected';
  owner: string;
  sourceArtifact: string;
  definition?: string | null;
  numeratorDenominator?: string | null;
  cohortOrSiteClass?: string | null;
  methodAndExclusions?: string | null;
  approvedAt?: string | null;
  reviewAt: string;
  allowedRoutes?:
    | {
        route: string;
        id?: string | null;
      }[]
    | null;
  allowedLocales: ('en' | 'id')[];
  customerPermission?: boolean | null;
  legalPermission?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Industry use cases shown on the Use Cases page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases".
 */
export interface UseCase {
  id: number;
  solutionType: 'shared' | 'retail' | 'mall';
  industryName: string;
  slug: string;
  /**
   * Lucide icon name
   */
  icon?: string | null;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  solutions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  relatedFeatures?: (number | Feature)[] | null;
  relatedUseCases?: (number | UseCase)[] | null;
  prerequisites?: string | null;
  limitations?: string | null;
  evidenceStatus: 'permissioned' | 'illustrative' | 'none';
  evidenceOwner?: string | null;
  reviewedAt?: string | null;
  /**
   * Approved claim records supporting public copy.
   */
  claimRecords?: (number | Claim)[] | null;
  publiclyApproved?: boolean | null;
  sortOrder?: number | null;
  isVisible?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Pricing packages on the Packages page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers".
 */
export interface PricingTier {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  features?:
    | {
        featureText: string;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  isFeatured?: boolean | null;
  /**
   * Required before this package can render publicly.
   */
  isVisible?: boolean | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions & answers on the FAQ page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * e.g. general, installation, analytics, pricing, technical
   */
  category?: string | null;
  sortOrder?: number | null;
  publiclyApproved?: boolean | null;
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Form submissions from contact and demo request pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  /**
   * Source form type
   */
  formType: 'contact' | 'demo';
  /**
   * Retail, Mall, or shared context selected by the visitor
   */
  solution: 'shared' | 'retail' | 'mall';
  email: string;
  /**
   * Update status after reviewing or replying
   */
  status?: ('new' | 'read' | 'replied') | null;
  /**
   * Full form data (name, phone, company, message, etc.)
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Deployment dots on the Indonesia map.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployment-locations".
 */
export interface DeploymentLocation {
  id: number;
  /**
   * City name shown on hover and as label
   */
  cityName: string;
  /**
   * e.g. 106.85 for Jakarta
   */
  longitude: number;
  /**
   * e.g. -6.2 for Jakarta (negative = south)
   */
  latitude: number;
  /**
   * Major city = bigger dot + always show label
   */
  isMajor?: boolean | null;
  deploymentType: 'unverified' | 'retail' | 'mall' | 'mixed';
  provenanceSource?: string | null;
  activeSince?: string | null;
  permissionStatus: 'unreviewed' | 'approved' | 'expired' | 'revoked';
  reviewAt?: string | null;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client logos shown in the homepage carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos".
 */
export interface ClientLogo {
  id: number;
  /**
   * Used as the logo alt text and record name.
   */
  companyName: string;
  /**
   * Upload PNG, JPG, WebP, or SVG. White edge backgrounds, excess margins, and square/portrait sizing are normalized automatically.
   */
  logo: number | Media;
  darkModeLogo?: (number | null) | Media;
  /**
   * Optional. Makes the logo clickable.
   */
  websiteUrl?: string | null;
  isVisible?: boolean | null;
  permissionStatus: 'unreviewed' | 'approved' | 'expired' | 'revoked';
  customerStatus: 'unverified' | 'active' | 'former';
  moduleScope?: string | null;
  siteScope?: string | null;
  permissionDate?: string | null;
  reviewAt?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'use-cases';
        value: number | UseCase;
      } | null)
    | ({
        relationTo: 'pricing-tiers';
        value: number | PricingTier;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'deployment-locations';
        value: number | DeploymentLocation;
      } | null)
    | ({
        relationTo: 'client-logos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  status?: T;
  isVisible?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  stableId?: T;
  name?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  longDescription?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  useCaseExamples?:
    | T
    | {
        text?: T;
        id?: T;
      };
  relatedFeatures?: T;
  image?: T;
  productTruth?:
    | T
    | {
        solutionType?: T;
        publicAvailability?: T;
        commercialEntitlement?: T;
        requirements?:
          | T
          | {
              cctv?: T;
              sensor?: T;
              gpu?: T;
              pos?: T;
              floorPlan?: T;
              network?: T;
              other?: T;
            };
        inputAndPrerequisites?: T;
        outputDefinition?: T;
        unitAndTimeWindow?: T;
        updateBehavior?: T;
        measurementScope?: T;
        retailMeaning?: T;
        mallMeaning?: T;
        decisionSupported?: T;
        limitationsAndValidation?: T;
      };
  evidence?:
    | T
    | {
        mediaStatus?: T;
        owner?: T;
        reviewedAt?: T;
      };
  claimRecords?: T;
  publiclyApproved?: T;
  sortOrder?: T;
  isVisible?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  solutionType?: T;
  industryName?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  longDescription?: T;
  challenges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  solutions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  relatedFeatures?: T;
  relatedUseCases?: T;
  prerequisites?: T;
  limitations?: T;
  evidenceStatus?: T;
  evidenceOwner?: T;
  reviewedAt?: T;
  claimRecords?: T;
  publiclyApproved?: T;
  sortOrder?: T;
  isVisible?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers_select".
 */
export interface PricingTiersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  features?:
    | T
    | {
        featureText?: T;
        included?: T;
        id?: T;
      };
  isFeatured?: T;
  isVisible?: T;
  ctaText?: T;
  ctaLink?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  publiclyApproved?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  solution?: T;
  email?: T;
  status?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployment-locations_select".
 */
export interface DeploymentLocationsSelect<T extends boolean = true> {
  cityName?: T;
  longitude?: T;
  latitude?: T;
  isMajor?: T;
  deploymentType?: T;
  provenanceSource?: T;
  activeSince?: T;
  permissionStatus?: T;
  reviewAt?: T;
  isVisible?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  companyName?: T;
  logo?: T;
  darkModeLogo?: T;
  websiteUrl?: T;
  isVisible?: T;
  permissionStatus?: T;
  customerStatus?: T;
  moduleScope?: T;
  siteScope?: T;
  permissionDate?: T;
  reviewAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  provenanceStatus?: T;
  source?: T;
  owner?: T;
  capturedAt?: T;
  permissionStatus?: T;
  approvedLocales?: T;
  approvedRoutes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  reviewAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  key?: T;
  approvedSentence?: T;
  claimType?: T;
  status?: T;
  owner?: T;
  sourceArtifact?: T;
  definition?: T;
  numeratorDenominator?: T;
  cohortOrSiteClass?: T;
  methodAndExclusions?: T;
  approvedAt?: T;
  reviewAt?: T;
  allowedRoutes?:
    | T
    | {
        route?: T;
        id?: T;
      };
  allowedLocales?: T;
  customerPermission?: T;
  legalPermission?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Brand name shown in browser tab and SEO
   */
  siteName?: string | null;
  /**
   * Short tagline for SEO meta description and social sharing
   */
  siteDescription?: string | null;
  /**
   * Enable public company/contact proof only after owner review.
   */
  identityVerified?: boolean | null;
  legalName?: string | null;
  productOperator?: string | null;
  /**
   * Main logo used in header and footer
   */
  logo?: (number | null) | Media;
  /**
   * Small icon shown in browser tab (recommended: 32x32 PNG)
   */
  favicon?: (number | null) | Media;
  /**
   * Shown only after identity/contact review.
   */
  contactEmail?: string | null;
  /**
   * Phone number with country code.
   */
  contactPhone?: string | null;
  /**
   * Office address shown in footer
   */
  contactAddress?: string | null;
  supportHours?: string | null;
  responseExpectation?: string | null;
  /**
   * Verified WhatsApp number without +.
   */
  whatsappNumber?: string | null;
  formPrivacyUrl?: string | null;
  socialLinks?: {
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  /**
   * Google Analytics tracking ID (e.g. G-XXXXXXXXXX)
   */
  googleAnalyticsId?: string | null;
  /**
   * Default image for social media sharing (recommended: 1200x630)
   */
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  identityVerified?: T;
  legalName?: T;
  productOperator?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  supportHours?: T;
  responseExpectation?: T;
  whatsappNumber?: T;
  formPrivacyUrl?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
      };
  googleAnalyticsId?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}